//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaseRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.BaseRes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 AllowDelete 的本地化字符串。
        /// </summary>
        internal static string AllowDelete {
            get {
                return ResourceManager.GetString("AllowDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 AllowEdit 的本地化字符串。
        /// </summary>
        internal static string AllowEdit {
            get {
                return ResourceManager.GetString("AllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Sorrry! You do not have authority to do this! 的本地化字符串。
        /// </summary>
        internal static string AuthorityMsg {
            get {
                return ResourceManager.GetString("AuthorityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 BaseInfo 的本地化字符串。
        /// </summary>
        internal static string BaseInfo {
            get {
                return ResourceManager.GetString("BaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 CreaterTime 的本地化字符串。
        /// </summary>
        internal static string CreaterTime {
            get {
                return ResourceManager.GetString("CreaterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 CreaterUserId 的本地化字符串。
        /// </summary>
        internal static string CreaterUserId {
            get {
                return ResourceManager.GetString("CreaterUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Prompt：Are you sure you want to delete this？ 的本地化字符串。
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Details 的本地化字符串。
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Businessrole 的本地化字符串。
        /// </summary>
        internal static string Duty_BusinessRole {
            get {
                return ResourceManager.GetString("Duty_BusinessRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 OtherRole 的本地化字符串。
        /// </summary>
        internal static string Duty_OtherRole {
            get {
                return ResourceManager.GetString("Duty_OtherRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 SystemRole 的本地化字符串。
        /// </summary>
        internal static string Duty_SystemRole {
            get {
                return ResourceManager.GetString("Duty_SystemRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 EnabledFlag 的本地化字符串。
        /// </summary>
        internal static string EnabledFlag {
            get {
                return ResourceManager.GetString("EnabledFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 EnCode 的本地化字符串。
        /// </summary>
        internal static string EnCode {
            get {
                return ResourceManager.GetString("EnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Incorrect user name or password 的本地化字符串。
        /// </summary>
        internal static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Rapid development platform 的本地化字符串。
        /// </summary>
        internal static string FastDevPlatForm {
            get {
                return ResourceManager.GetString("FastDevPlatForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 FirstPage 的本地化字符串。
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Please input 的本地化字符串。
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 One row has been selected 的本地化字符串。
        /// </summary>
        internal static string ItemSelected {
            get {
                return ResourceManager.GetString("ItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Please Enter The Keywords 的本地化字符串。
        /// </summary>
        internal static string KeyWord {
            get {
                return ResourceManager.GetString("KeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 LastUpdateTime 的本地化字符串。
        /// </summary>
        internal static string LastUpdateTime {
            get {
                return ResourceManager.GetString("LastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 LastUpdateUserId 的本地化字符串。
        /// </summary>
        internal static string LastUpdateUserId {
            get {
                return ResourceManager.GetString("LastUpdateUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 ForgetPassword 的本地化字符串。
        /// </summary>
        internal static string Login_ForgetPwd {
            get {
                return ResourceManager.GetString("Login_ForgetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Login successful, jumping... 的本地化字符串。
        /// </summary>
        internal static string Login_LoginSuccess {
            get {
                return ResourceManager.GetString("Login_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 RememberPassword 的本地化字符串。
        /// </summary>
        internal static string Login_RememberPwd {
            get {
                return ResourceManager.GetString("Login_RememberPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 UserName 的本地化字符串。
        /// </summary>
        internal static string Login_UserName {
            get {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Welcome 的本地化字符串。
        /// </summary>
        internal static string Login_Welcome {
            get {
                return ResourceManager.GetString("Login_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 ClickHereToChangeIcon 的本地化字符串。
        /// </summary>
        internal static string Module_ChangeIcon {
            get {
                return ResourceManager.GetString("Module_ChangeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 EditOptionCode 的本地化字符串。
        /// </summary>
        internal static string Module_EditOpCode {
            get {
                return ResourceManager.GetString("Module_EditOpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Expand 的本地化字符串。
        /// </summary>
        internal static string Module_Expand {
            get {
                return ResourceManager.GetString("Module_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Icon 的本地化字符串。
        /// </summary>
        internal static string Module_Icon {
            get {
                return ResourceManager.GetString("Module_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Menu 的本地化字符串。
        /// </summary>
        internal static string Module_Menu {
            get {
                return ResourceManager.GetString("Module_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 ModuleId 的本地化字符串。
        /// </summary>
        internal static string Module_ModuleId {
            get {
                return ResourceManager.GetString("Module_ModuleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 OptionCode 的本地化字符串。
        /// </summary>
        internal static string Module_OpCode {
            get {
                return ResourceManager.GetString("Module_OpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Public 的本地化字符串。
        /// </summary>
        internal static string Module_Public {
            get {
                return ResourceManager.GetString("Module_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 CreateOptionCode 的本地化字符串。
        /// </summary>
        internal static string Mudule_CreateOpCode {
            get {
                return ResourceManager.GetString("Mudule_CreateOpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 DeletOptionCode 的本地化字符串。
        /// </summary>
        internal static string Mudule_DeletOpCode {
            get {
                return ResourceManager.GetString("Mudule_DeletOpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 FramePage 的本地化字符串。
        /// </summary>
        internal static string Mudule_FramePage {
            get {
                return ResourceManager.GetString("Mudule_FramePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 NewWindow 的本地化字符串。
        /// </summary>
        internal static string Mudule_NewWindow {
            get {
                return ResourceManager.GetString("Mudule_NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 NoPage 的本地化字符串。
        /// </summary>
        internal static string Mudule_NoPage {
            get {
                return ResourceManager.GetString("Mudule_NoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 PopUpPage 的本地化字符串。
        /// </summary>
        internal static string Mudule_PopUpPage {
            get {
                return ResourceManager.GetString("Mudule_PopUpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Target 的本地化字符串。
        /// </summary>
        internal static string Mudule_Target {
            get {
                return ResourceManager.GetString("Mudule_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 UrlAddress 的本地化字符串。
        /// </summary>
        internal static string Mudule_UrlAddress {
            get {
                return ResourceManager.GetString("Mudule_UrlAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 EndTime 的本地化字符串。
        /// </summary>
        internal static string Office_EndTime {
            get {
                return ResourceManager.GetString("Office_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 StartTime 的本地化字符串。
        /// </summary>
        internal static string Office_StartTime {
            get {
                return ResourceManager.GetString("Office_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 OptionCode 的本地化字符串。
        /// </summary>
        internal static string OptionCode {
            get {
                return ResourceManager.GetString("OptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 OptionName 的本地化字符串。
        /// </summary>
        internal static string OptionName {
            get {
                return ResourceManager.GetString("OptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 OrganizeName 的本地化字符串。
        /// </summary>
        internal static string OrganizeName {
            get {
                return ResourceManager.GetString("OrganizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string Organize_Address {
            get {
                return ResourceManager.GetString("Organize_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Bloc 的本地化字符串。
        /// </summary>
        internal static string Organize_Bloc {
            get {
                return ResourceManager.GetString("Organize_Bloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Company 的本地化字符串。
        /// </summary>
        internal static string Organize_Company {
            get {
                return ResourceManager.GetString("Organize_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Department 的本地化字符串。
        /// </summary>
        internal static string Organize_Department {
            get {
                return ResourceManager.GetString("Organize_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string Organize_Email {
            get {
                return ResourceManager.GetString("Organize_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Fax 的本地化字符串。
        /// </summary>
        internal static string Organize_Fax {
            get {
                return ResourceManager.GetString("Organize_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Group 的本地化字符串。
        /// </summary>
        internal static string Organize_Group {
            get {
                return ResourceManager.GetString("Organize_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Manager 的本地化字符串。
        /// </summary>
        internal static string Organize_ManagerId {
            get {
                return ResourceManager.GetString("Organize_ManagerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 MobilePhone 的本地化字符串。
        /// </summary>
        internal static string Organize_MobilePhone {
            get {
                return ResourceManager.GetString("Organize_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Telephone 的本地化字符串。
        /// </summary>
        internal static string Organize_Tel {
            get {
                return ResourceManager.GetString("Organize_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 WeChat 的本地化字符串。
        /// </summary>
        internal static string Organize_WeChat {
            get {
                return ResourceManager.GetString("Organize_WeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 ColumnId 的本地化字符串。
        /// </summary>
        internal static string Page_ColInfoId {
            get {
                return ResourceManager.GetString("Page_ColInfoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 ColumnName 的本地化字符串。
        /// </summary>
        internal static string Page_ColInfoName {
            get {
                return ResourceManager.GetString("Page_ColInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Num 的本地化字符串。
        /// </summary>
        internal static string Page_dataNum {
            get {
                return ResourceManager.GetString("Page_dataNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 PageId 的本地化字符串。
        /// </summary>
        internal static string Page_Id {
            get {
                return ResourceManager.GetString("Page_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 IsSeparatePage 的本地化字符串。
        /// </summary>
        internal static string Page_ifSeparatePage {
            get {
                return ResourceManager.GetString("Page_ifSeparatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 InformationId 的本地化字符串。
        /// </summary>
        internal static string Page_InfoId {
            get {
                return ResourceManager.GetString("Page_InfoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Infomation 的本地化字符串。
        /// </summary>
        internal static string Page_InfoName {
            get {
                return ResourceManager.GetString("Page_InfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 No 的本地化字符串。
        /// </summary>
        internal static string Page_NoSeparatePage {
            get {
                return ResourceManager.GetString("Page_NoSeparatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string Page_SeparatePage {
            get {
                return ResourceManager.GetString("Page_SeparatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 ParentNode 的本地化字符串。
        /// </summary>
        internal static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 PrimaryKey 的本地化字符串。
        /// </summary>
        internal static string PrimaryKey {
            get {
                return ResourceManager.GetString("PrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 PleaseSelect 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Order 的本地化字符串。
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Superior 的本地化字符串。
        /// </summary>
        internal static string Superior {
            get {
                return ResourceManager.GetString("Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string Sys_Value {
            get {
                return ResourceManager.GetString("Sys_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
